### ISSUE TITLE
Cannot find project file

### ISSUE THREAD

**Issue by habakuk007** [LarsSkovslund/NuGet.Package.Builder#1]
Thanks for your Application.

In one of my projects I tried to add it i get this error during compilation:

	1>__BuildNuGetPackage:
	1>  "C:\US\packages\NuGet.Package.Builder.1.0.6\tools\NuGet.Package.Builder.exe" --path "C:\US\packages\NuGet.Package.Builder.1.0.6\tools" -t "Logima.BuildingBlocks.UsageStatistics" -e .vbproj -p "Configuration=Release;Platform=AnyCPU" -o "C:\US\Logima.BuildingBlocks.UsageStatistics\bin\Release" -w "C:\US\Logima.BuildingBlocks.UsageStatistics"    
	1>  "C:\US\packages\NuGet.Package.Builder.1.0.6\tools\NuGet.Package.Builder.exe" --path "C:\US\packages\NuGet.Package.Builder.1.0.6\tools" -t "Logima.BuildingBlocks.UsageStatistics" -e .vbproj -p "Configuration=Release;Platform=AnyCPU" -o "C:\US\Logima.BuildingBlocks.UsageStatistics\bin\Release" -w "C:\US\Logima.BuildingBlocks.UsageStatistics"    
	1>  C:\US\packages\NuGet.Package.Builder.1.0.6\tools\NuGet.exe pack "C:\US\Logima.BuildingBlocks.UsageStatistics\Logima.BuildingBlocks.UsageStatistics.vbproj"  -NoDefaultExcludes -Verbosity Detailed -Properties "OutDir=C:\US\Logima.BuildingBlocks.UsageStatistics\bin\Release;Configuration=Release;Platform=AnyCPU" -NonInteractive -OutputDirectory "C:\US\Logima.BuildingBlocks.UsageStatistics\bin\Release" -basepath "C:\US\Logima.BuildingBlocks.UsageStatistics\bin\Release" -IncludeReferencedProjects
	1>  Es wird versucht, das Paket aus "Logima.BuildingBlocks.UsageStatistics.vbproj" zu erstellen.
	1>C:\US\packages\NuGet.Package.Builder.1.0.6\build\NuGet.Package.Builder.targets(28,3): error : Microsoft.Build.Exceptions.InvalidProjectFileException: Die Projektdatei konnte nicht geladen werden. Die Datei "C:\US\Logima.BuildingBlocks.UsageStatistics\Logima.BuildingBlocks.UsageStatistics.vbproj" konnte nicht gefunden werden.  C:\US\Logima.BuildingBlocks.UsageStatistics\Logima.BuildingBlocks.UsageStatistics.vbproj ---> System.IO.FileNotFoundException: Die Datei "C:\US\Logima.BuildingBlocks.UsageStatistics\Logima.BuildingBlocks.UsageStatistics.vbproj" konnte nicht gefunden werden.

That's right, as my project file has this name:

    C:\US\Logima.BuildingBlocks.UsageStatistics\UsageStatistics.vbproj

Any idea how to fix this (beside of changing the name of the project file)?

Ciao!
   Stefan

**Comment by LarsSkovslund** [comment]
Hi Stefan,

I tried a simple VB class library and it worked fine, what kind/type of VB project are causing the problems? 

Cheers
  Lars

**Comment by LarsSkovslund** [comment]
Hi Stefan,

I have now identified the issue and it's a bug where I used the target name (name of dll or exe) instead of using the Project name.

Your project file is named 'UsageStatistics.vbproj' but your output file name is 'Logima.BuildingBlocks.UsageStatistics.dll (exe)'.

I'll fix this ASAP.

Cheers
  Lars

**Comment by LarsSkovslund** [comment]
Release 1.0.7 now on nuget

**Comment by habakuk007** [comment]
Thanks! That was a fast fix :smile: it works now :+1:

**Comment by Peuczynski** [comment]
Hi, I wanted to create new issue but I think this is related so this one, despite it's closed. This is not really "issue" issue, rather "something Lars would want to know" issue.

I use 1.0.8 version. My project name is Logger.csproj. This project's output assembly is THE.Logger.dll. With that configuration I cannot push the package to my NuGet server because the package name is THE.Logger* (assembly) while the script looks for Logger* (project file). The solution to this is to edit the nuspec file and manually define the package name. This is not a problem for me but it may be very confusing for many users.

What is confusing for me is that you seem to change the behaviour to use project file name in version 1.0.7 if I am not mistaken.

If you want me to explain why it is important for us to have assembly names that project names I can explain. If you want to discuss the package naming approach or require some other help with this matter I am at your disposal.

**Comment by LarsSkovslund** [comment]
Hi Peuczynski,

Thanks for bringing this to my attention.

You are absolutely right I only fixed the package building issue when AssemblyName differs from project name and failed to consider the publishing part.

I have now corrected the issue and released a version 1.0.9 on nuget so please feel free to take it for a spin.

Cheers
  Lars

**Comment by Peuczynski** [comment]
Hi Lars,

works like charm!

Best regards,
Peuczynski
